import type { SourceSpan } from './ast'

export type ExpressionDiagnosticSeverity = 'error' | 'warning'

export type ExpressionDiagnosticCode =
  | 'SYNTAX_ERROR'
  | 'UNKNOWN_TABLE'
  | 'UNKNOWN_COLUMN'
  | 'COLUMN_OUTSIDE_ROW_CONTEXT'
  | 'TYPE_MISMATCH'
  | 'DIVISION_ERROR'
  | 'COLUMN_NAME_CONFLICT'
  | 'DUPLICATE_CALCULATED_COLUMN'
  | 'UNSUPPORTED_FUNCTION'
  | 'INVALID_FUNCTION_ARGUMENT'
  | 'RELATED_NO_RELATIONSHIP'
  | 'RELATED_INACTIVE_RELATIONSHIP'
  | 'RELATED_WRONG_DIRECTION'
  | 'RELATED_AMBIGUOUS_RELATIONSHIP'
  // Sprint 4 (Measures / FilterContext) — see docs/MEASURES.md and docs/FILTER_CONTEXT.md.
  | 'BARE_TABLE_REFERENCE'
  | 'UNKNOWN_MEASURE'
  | 'DUPLICATE_MEASURE'
  | 'MEASURE_DEPENDENCY_CYCLE'
  | 'COLUMN_REQUIRES_AGGREGATION'
  | 'INVALID_AGGREGATION_ARGUMENT'
  | 'NON_NUMERIC_AGGREGATION'
  | 'FILTER_GRAPH_INVALID'
  | 'INVALID_FILTER_VALUE'
  | 'RELATED_REQUIRES_ROW_CONTEXT'
  // Sprint 8 (CALCULATE) — see docs/CALCULATE.md.
  | 'INVALID_CALCULATE_ARITY'
  | 'CALCULATE_INVALID_FILTER_ARGUMENT'
  | 'BOOLEAN_FILTER_MULTIPLE_TABLES'
  | 'BOOLEAN_FILTER_MEASURE_REFERENCE'
  | 'BOOLEAN_FILTER_NESTED_CALCULATE'
  | 'FILTER_PREDICATE_NOT_BOOLEAN'
  | 'FILTER_ROW_CONTEXT_VIOLATION'
  | 'INVALID_REMOVEFILTERS_ARGUMENT'
  | 'INVALID_ALL_ARGUMENT'
  | 'CALCULATE_CONTEXT_TRANSITION_NOT_SUPPORTED'
  // Sprint 9 (Iterators / Table Expressions / Conditional Logic) — see docs/ITERATORS.md and docs/TABLE_EXPRESSIONS.md.
  | 'INVALID_ITERATOR_ARGUMENT'
  | 'ITERATOR_TABLE_REQUIRED'
  | 'ITERATOR_EXPRESSION_TYPE_ERROR'
  | 'ITERATOR_ROW_SCOPE_VIOLATION'
  | 'ITERATOR_UNSUPPORTED_TABLE_EXPRESSION'
  | 'ITERATOR_CONTEXT_TRANSITION_ERROR'
  | 'ITERATOR_CALCULATE_CONTEXT_TRANSITION_NOT_SUPPORTED'
  | 'INVALID_VALUES_ARGUMENT'
  | 'INVALID_DISTINCT_ARGUMENT'
  | 'INVALID_TABLE_EXPRESSION_ARGUMENT'
  | 'IF_INVALID_ARITY'
  | 'IF_CONDITION_NOT_BOOLEAN'
  | 'INVALID_SWITCH_ARGUMENT'
  | 'SELECTEDVALUE_INVALID_ARGUMENT'
  // Sprint 10 (Date Tables / Time Intelligence) — see docs/DATE_TABLES.md and docs/TIME_INTELLIGENCE.md.
  | 'DATE_TABLE_REQUIRED'
  | 'TIME_INTELLIGENCE_INVALID_ARGUMENT'
  | 'DATEADD_INVALID_INTERVAL'
  | 'DATEADD_INTERVAL_COUNT_INVALID'
  | 'DATEADD_NON_CONTIGUOUS_CONTEXT'
  | 'TOTALYTD_INVALID_ARGUMENT'
  // Sprint 11 (Advanced Relationships / USERELATIONSHIP / CROSSFILTER) — see docs/USERELATIONSHIP.md.
  | 'RELATED_UNSUPPORTED_CARDINALITY'
  | 'USERELATIONSHIP_INVALID_ARITY'
  | 'USERELATIONSHIP_COLUMN_REQUIRED'
  | 'USERELATIONSHIP_RELATIONSHIP_NOT_FOUND'
  | 'USERELATIONSHIP_AMBIGUOUS_RELATIONSHIP'
  | 'USERELATIONSHIP_INVALID_CONTEXT'
  | 'CROSSFILTER_INVALID_ARITY'
  | 'CROSSFILTER_COLUMN_REQUIRED'
  | 'CROSSFILTER_RELATIONSHIP_NOT_FOUND'
  | 'CROSSFILTER_AMBIGUOUS_RELATIONSHIP'
  | 'CROSSFILTER_INVALID_DIRECTION'
  | 'CROSSFILTER_DIRECTION_INVALID_FOR_CARDINALITY'
  | 'CROSSFILTER_INVALID_CONTEXT'
  | 'PROPAGATION_DID_NOT_CONVERGE'

export interface ExpressionDiagnostic {
  severity: ExpressionDiagnosticSeverity
  code: ExpressionDiagnosticCode
  message: string
  span?: SourceSpan
  details?: Record<string, unknown>
}

export function diagnostic(
  severity: ExpressionDiagnosticSeverity,
  code: ExpressionDiagnosticCode,
  message: string,
  span?: SourceSpan,
  details?: Record<string, unknown>,
): ExpressionDiagnostic {
  return { severity, code, message, span, details }
}

export function hasError(diagnostics: ExpressionDiagnostic[]): boolean {
  return diagnostics.some((d) => d.severity === 'error')
}
